services:
  - type: web
    name: tailored-resume-server
    runtime: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
    buildCommand: docker build -t tailored-resume-server .
    startCommand: docker run -p 10000:10000 tailored-resume-server 