services:
  - type: web
    name: latex-compiler-api
    runtime: docker
    region: oregon
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DOCKER_BUILDKIT
        value: "1" 