services:
  - type: web
    name: latex-compiler-api
    runtime: docker
    region: oregon
    plan: free
    rootDir: server
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
    buildCommand: docker build -t latex-compiler-api .
    startCommand: docker run -p $PORT:$PORT latex-compiler-api 